version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dependabot:"
    labels:
      - "bot"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dependabot:"
    labels:
      - "bot"
