analyzer:
  errors:
    use_setters_to_change_properties: ignore
  exclude:
    - "**/*.g.dart" # Exclude generated files
    - "**/*.freezed.dart" # Exclude Freezed-generated files (if applicable)
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
