name: smart_cal
description: Smart Cal
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  clock: ^1.1.2
  drift: ^2.23.1
  drift_db_viewer: ^2.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  sqlcipher_flutter_libs: ^0.6.4
  sqlite3: ^2.5.0
  table_calendar: ^3.1.3
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.14
  drift_dev: ^2.23.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.3
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
