name: smart_cal
description: Smart Cal
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  clock: ^1.1.2
  drift: ^2.28.1
  drift_db_viewer: ^2.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  freezed_annotation: ^3.1.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  path_provider: ^2.1.5
  riverpod_annotation: ^3.0.0
  sqlcipher_flutter_libs: ^0.6.8
  sqlite3: ^2.7.5
  table_calendar: ^3.1.3
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.6.0
  drift_dev: ^2.28.2
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true
