name: smart_cal
description: Smart Cal
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  riverpod_annotation: ^2.6.1
  table_calendar: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
